### ISSUE TITLE
Empty page rather than error or confirmation if only email is filled in

### ISSUE THREAD

**Issue by nighthawk** [ExternalTesters/ExternalTesters-public#8]
When you sign up and don't fill in all the fields, you land on an empty page and no confirmation mail is sent. Please fix urgently as this might cause people to believe they signed up but didn't—especially an issue if someone only enters their email address!

**Comment by HendX** [comment]
Just added an error message screen that tells the user to go back and fill out all forms.

Ideally in future the form will redisplay here with pre-filled items, but this was a quick patch. I'll close it and open a new issue to deal with improvements.
